# Generated by Django 5.1.3 on 2025-02-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_pedido_itempedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Preparo', 'Em Preparo'), ('Saiu para Entrega', 'Saiu para Entrega'), ('Entregue', 'Entregue')], default='Pendente', max_length=20),
        ),
    ]
