# Generated by Django 5.1.3 on 2025-02-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_pedido_endereco_entrega_pedido_metodo_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='endereco_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_pagamento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], max_length=10, null=True),
        ),
    ]
